### PR TITLE
Add basic support for 65el02

### PR DESCRIPTION
**Pull request by Shadlock0133**

### CODE REVIEW

**Comment by seanahan5000** [comment]
Do you know of any projects that use this 6502 variant?  I can only find references to some Minecraft mod from 12 years ago.  I can add support for it in my next release since it looks like ACME and 64TASS support it and I'm doing some 65C02 and 65816 work anyway, but it would nice to have some real source code to test against.

**Comment by Shadlock0133** [comment]
https://github.com/Shadlock0133/emu65el02/blob/9fb1cff8e4c28752f0845d3b8041b5718c166f70/redforthxp.dis.asm

**Comment by seanahan5000** [comment]
Version 1.4.0 of the extension now supports 65EL02.  Try it out and let me know if it works for you.

**Comment by Shadlock0133** [comment]
yep, it works. new opcodes are missing the popup windows with info, but not a big issue. thanks!

**Comment by seanahan5000** [comment]
Yes, the popup window issue will get fixed by other changes to be made later.  If you're running your own build of the extension, you can change line 733 in server/src/lsp_server.ts from this:

            const isa = isaSet65xx.getIsa("65816")

To this:

            const isa = isaSet65xx.getIsa("65el02")

**Pull request closed without merging**
